# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Generate
      run: go generate

    - name: hlsjsdownloader
      run: cd /home/runner/go/pkg/mod/github.com/mutsimutsi/mediamtx@v1.0.0/internal/servers/hls
        go run ./hlsjsdownloader

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
